### ISSUE TITLE
Ruby indent is 2 spaces

### ISSUE THREAD

**Issue by stephaneliu** [SolarisFlare/dtg#1]
https://github.com/SolarisFlare/dtg/blob/8b990adbde82aff0cc779fc88f4b47411c494586/lib/dtg/core_ext.rb#L2

**Comment by optimizasean** [comment]
Thank you, I had my vim configured strangely.  Just updated all files to 2 spaces and removed trailing whitespace and added good practice with overcommit and a handful of gems.
